version: '3.4'

services:
  new-api:
    image: new-api-ssc:v1.4
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "33016:3000"
    volumes:
      - /vol1/1000/Data1/Docker/new-api/data-ssc:/data
      - /vol1/1000/Data1/Docker/new-api/data-ssc/logs:/app/logs
    environment:
      - SQL_DSN=root:root@tcp(192.168.31.197:3306)/oneapi_ssc
      - TZ=Asia/Shanghai
      - REQUEST_LOG_ENABLED=false
      - AUTO_SLOW_THRESHOLD_MS=10000
      - AUTO_ADVANCED_ENABLED=true
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
